FROM debian:bullseye

# RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak \
#     && sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    wget \
    vim \
    git \
    ffmpeg \
    xz-utils \
    zsh \
    build-essential \
    unzip \
    htop \
    less \
    tmux \
    iputils-ping \
    net-tools \
    rsync \
    cmake \
    sudo \
    openssh-client \
    nodejs \
    npm \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN update-ca-certificates

RUN GO_VERSION=1.23.4 \
    && ARCH=$(dpkg --print-architecture) \
    && sudo wget https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz \
    && sudo rm -rf /usr/local/go \
    && sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-${ARCH}.tar.gz \
    && sudo rm go${GO_VERSION}.linux-${ARCH}.tar.gz \
    && echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc

COPY . /rss-reader
WORKDIR /rss-reader

SHELL ["/bin/bash", "-c"]
RUN source ~/.bashrc && make build-backend install-frontend

CMD [ "bash", "-c", "hack/run.sh" ]

